### ISSUE TITLE
NameError: name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by moznpan** [wwoods/keras_pickle_wrapper#4]
Thanks for making this. It seems like the setup.py file is breaking installs in python 2.7.

```
pip install keras-pickle-wrapper
Collecting keras-pickle-wrapper
  Downloading keras-pickle-wrapper-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qxEyzT/keras-pickle-wrapper/setup.py", line 8, in <module>
        except FileNotFoundError:
    NameError: name 'FileNotFoundError' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qxEyzT/keras-pickle-wrapper/
```
 Removing the FileNotFoundError exception and replacing it with a generic one works though.
```
#except FileNotFoundError:
except:
    # Doesn't need to be in PyPI package.
    long_desc = None
```

**Comment by wwoods** [comment]
Fixed; thanks for mentioning this.

**Comment by moznpan** [comment]
No problem. Thanks for making this.
